name: Client

on:
  push:
    branches: 
      - 'main'
    paths:
      - '.github/workflows/checks-client.yml'
      - 'client/**'
  pull_request:
    branches: 
      - 'main'
    paths:
      - '.github/workflows/checks-client.yml'
      - 'client/**'

jobs:
  build_client:
    name: Build Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.5.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check
        run: pnpm check
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm test --if-present
